### ISSUE TITLE
(Spike - Devops) Investigacion de workflow

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/sprint-2#14]
## Descripción
Se desea tener la documentación extensiva sobre que es un Workflow

## Tareas
* [x] : Identificar al menos tres herramientas de automatización de workflow que sean compatibles con nuestro stack tecnológico actual.
* [x] : Evaluar las herramientas identificadas en términos de facilidad de integración, coste, y beneficios a largo plazo.

> 

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 27-04-2024

**Comment by optic4l** [comment]
# Que es un Workflow?
Un workflow es un conjunto de procesos, herramientas y prácticas que se utilizan para gestionar el ciclo de vida de desarrollo, pruebas, implementación y operaciones de software en un proyecto. Este flujo de trabajo tiene como objetivo principal mejorar la colaboración entre equipos, acelerar la entrega de software y garantizar su calidad y fiabilidad.

Un workflow puede abarcar varias areas, siendo típicamente las siguientes:

- **Planificación**: Esta etapa implica definir los requisitos para el nuevo software y crear un plan para el desarrollo y el despliegue.
- **Desarrollo**: Incluye la escritura de código, la revisión de código, la gestión de versiones y ramas, y la integración de cambios en el repositorio de código principal.
- **Integración continua (CI)**: Automatización de la compilación de código, ejecución de pruebas automatizadas, análisis estático de código y generación de artefactos de distribución en respuesta a cambios en el repositorio de código.
- **Entrega continua (CD)**: Automatización del despliegue de aplicaciones en entornos de prueba y producción, incluyendo la compilación, prueba, empaquetado, firma y distribución de artefactos de software.
- **Operaciones**: Esto incluye la configuración de herramientas de monitoreo y registro para recopilar datos sobre el rendimiento y la disponibilidad de la aplicación en producción, y responder rápidamente a problemas o incidencias. Como también, automatización de la creación, configuración y gestión de recursos de infraestructura, como servidores, redes, contenedores y bases de datos.

# Herramientas
Existen diversas herramientas para facilitar el trabajo que se pueden implementar en los flujos de trabajo dependiendo de la etapa del ciclo de vida del software en la que nos encontremos. Por ejemplo para la etapa de planificación tenemos herramientas como Trello, Teams, Lucidchart, entre otras, que facilitan la colaboración en esta etapa tan importante como lo es la planificación de un proyecto.

En esta ocasión se van a destacar diversas herramientas que nos permitan optimizar nuestro flujo de trabajo enfocándonos en las etapas de desarrollo y de CI/CD, teniendo en cuenta el stack tecnológico en el cual se esta desarrollando el proyecto.

### CodeMagic
Codemagic es un producto de integración continua y Entrega continua (CI/CD) basado en la nube diseñado específicamente para desarrolladores móviles que construyen aplicaciones con Flutter, React Native, iOS nativo, Android nativo, Unity, Kotlin Multiplatform Mobile y Ionic.

Codemagic automatiza el proceso de construcción, pruebas e implementación de aplicaciones en tiendas como Apple App Store, Google Play, Microsoft Store y Huawei App Gallery. Las nuevas builds se pueden activar cuando el código se pushea al repositorio, se añaden etiquetas o cuando las pull request se fusionan. Se pueden configurar múltiples flujos de trabajo para que la aplicación esté disponible para el equipo de desarrollo, distribuir la última compilación al equipo de pruebas o publicar la aplicación a producción.

Tiene un free tier la cual permite 500 minutos de build gratis por mes, luego comienza a regir el pricing pay as you go, con costos de:
- macOS M1 and Intel-based machines $0.095 / minute
- Linux and Windows machines $0.045 / minute
- Precio adicional por concurrencias $49 / concurrency
- Permite hasta 3 builds paralelas
### GitHub Actions
GitHub Actions es una característica integrada en la plataforma GitHub que permite automatizar flujos de trabajo directamente en los repositorios de código. Con GitHub Actions, se puede definir y ejecutar flujos de trabajo personalizados para realizar tareas automatizadas, como pruebas de código, compilación de software, despliegue de aplicaciones y mucho más.

GitHub actions permite crear un flujo de trabajo para cada evento de GitHub como los push, la creación de issues, o una nueva release de la aplicación.

Puede correr contenedores para diferentes sistemas operativos (Linux, macOS, Windows, ARM. Es compatible con cualquier lenguaje de programación, se pueden crear matrices de flujos de trabajo que prueben simultáneamente a trabes de multiples sistemas operativos y versiones en tiempo de ejecución.

Ademas, cuenta con multiples workflows que son impulsados por la comunidad, 
### Fastlane
Fastlane es una herramienta de código abierto utilizada principalmente para automatizar y agilizar el proceso de desarrollo y distribución de aplicaciones móviles para iOS y Android. Es una herramienta popular en el ecosistema de desarrollo de aplicaciones móviles, especialmente para proyectos que utilizan tecnologías como Flutter, React Native, Xamarin, y más.

Algunas de las características y funcionalidades principales de Fastlane incluyen:

1. **Automatización de tareas repetitivas**: Fastlane automatiza tareas repetitivas y tediosas en el proceso de desarrollo de aplicaciones móviles, como la compilación de código, la ejecución de pruebas, la generación de archivos de aplicación, la firma de aplicaciones y el despliegue en tiendas de 
2. **Gestión de certificados y perfiles de aprovisionamiento**: Fastlane simplifica la gestión de certificados de firma y perfiles de aprovisionamiento requeridos para el desarrollo y distribución de aplicaciones iOS. Puede generar automáticamente certificados de firma y perfiles de aprovisionamiento necesarios para firmar y distribuir aplicaciones 
3. **Despliegue continuo (CD)**: Fastlane facilita el proceso de implementación continua de aplicaciones móviles mediante la automatización del proceso de compilación, prueba y distribución de aplicaciones en tiendas de aplicaciones como la App Store de Apple y Google Play 
4. **Flujos de trabajo personalizables**: Fastlane ofrece una amplia gama de herramientas y acciones que puedes combinar y personalizar para crear flujos de trabajo de desarrollo y distribución de aplicaciones móviles personalizados según tus necesidades 
5. **Integración con herramientas de terceros**: Fastlane se integra con una variedad de herramientas y servicios populares utilizados en el desarrollo de aplicaciones móviles, como GitHub, Bitbucket, Firebase, TestFlight, entre otros.

Fastlane es la opción que nos proporciona la propia documentación de Flutter para realizar el despliegue continuo (CD). Si bien esta no es una plataforma de CI, se puede integrar fácilmente con otras herramientas populares para la implementación continua, como la que nos proporciona el mismo GitHub

**Comment by optic4l** [comment]
# Evaluación de alternativas

### Codemagic:
- Facilidad de uso: Codemagic está específicamente diseñado para proyectos de Flutter, lo que significa que ofrece una experiencia optimizada y fácil de usar para los desarrolladores de Flutter.
- Integración continua para Flutter: Codemagic está especialmente adaptado para el desarrollo de aplicaciones Flutter, lo que significa que incluye funcionalidades específicas para compilar, probar y distribuir aplicaciones Flutter de forma eficiente.
- Enfoque centrado en Flutter: Codemagic ofrece funcionalidades específicas para el desarrollo de aplicaciones Flutter, como la compatibilidad con Flutter doctor, soporte para pruebas de Flutter, y flujos de trabajo predefinidos optimizados para proyectos de Flutter.

### GitHub Actions:
- Integración nativa con GitHub: GitHub Actions está integrado directamente en GitHub, lo que significa que puedes definir y ejecutar flujos de trabajo directamente desde tu repositorio de GitHub.
- Flexibilidad y personalización: GitHub Actions es una plataforma más general que puede ser utilizada en una variedad de proyectos y tecnologías, lo que te permite crear flujos de trabajo personalizados utilizando una amplia gama de acciones predefinidas y complementos de la comunidad.
- Amplia comunidad y soporte: GitHub Actions cuenta con una gran comunidad de usuarios y una amplia documentación, lo que facilita la obtención de ayuda y soporte si es necesario.

### Fastlane:
- Automatización avanzada: Fastlane es una herramienta extremadamente poderosa y versátil que te permite automatizar una amplia gama de tareas relacionadas con el desarrollo y la distribución de aplicaciones móviles, incluyendo la compilación, prueba, firma y despliegue de aplicaciones.
- Gestión de certificados y perfiles: Fastlane simplifica la gestión de certificados de firma y perfiles de aprovisionamiento necesarios para el desarrollo y distribución de aplicaciones iOS.
- Amplia gama de acciones: Fastlane ofrece una amplia gama de acciones predefinidas y complementos que puedes combinar y personalizar para crear flujos de trabajo de desarrollo y distribución de aplicaciones móviles personalizados según tus necesidades específicas.

Si bien, Codemagic es la herramienta mas completa enfocada al uso y desarrollo con flutter que es nuestro stack tecnológico, esta no es una herramienta open source, por lo que dependiendo de nuestro consumo podría incurrir en un gasto innecesario. 

Así que para este caso, lo mas optimo seria utilizar las funcionalidades que nos ofrece GitHub, al ser de propósito general se puede aplicar a un mayor casos de usos aportando mas valor a nuestro perfil como profesionales no tan solo enfocado en Flutter, ademas, como ya se tiene el proyecto estructurado en GitHub, es mas provecho darle utilidad a la integración que GitHub actions tiene con los repositorios y el proyecto en su totalidad trabajado en GitHub.

También, hay que tener en cuenta la posibilidad de tener que incluir Fastlane para realizar una correcta gestión de los certificados de firma y perfiles de aprovisionamiento necesario para la distribución de la aplicación.
