### ISSUE TITLE
(Feature - Infraestructure) Modelo BD

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/sprint-2#19]
## Descripción
Implementación del modelo de base de datos para poder tener una idea más exacta de hacer la base de datos 

## Tareas
* [x] Tarea 1: Modela una tabla relacional (con sus respectivos atributos y carácter)
* [x] Tarea 2: Especificación de las claves primarias y análisis de las relaciones.
* [x] Tarea 3: Identifica tipos de entidades, atributos y relaciones.
* [x] Tarea 4: Normaliza para reducir redundancia y desnormaliza para mejorar el rendimiento

> Se debe conversar y realizar con el TL para tener una mejor comprension de la tarea

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 05-05-2024

**Comment by JoseMalcaR** [comment]
## Modelar tabla relacional

```sql
-- Tabla de Usuarios
CREATE TABLE Usuarios (
    id_usuario SERIAL PRIMARY KEY,
    nombre VARCHAR(255),
    correo_electronico VARCHAR(255),
    contrasena VARCHAR(255),
    saldo_ficticio DECIMAL(10, 2)
);

-- Tabla de Monedas
CREATE TABLE Monedas (
    id_moneda SERIAL PRIMARY KEY,
    nombre VARCHAR(255),
    simbolo VARCHAR(10)
);

-- Tabla de Transacciones
CREATE TABLE Transacciones (
    id_transaccion SERIAL PRIMARY KEY,
    id_usuario INTEGER,
    id_moneda INTEGER,
    tipo VARCHAR(10),
    cantidad DECIMAL(10, 2),
    precio_por_unidad DECIMAL(10, 2),
    fecha_transaccion DATE,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_moneda) REFERENCES Monedas(id_moneda)
);

-- Tabla de Precios Actuales
CREATE TABLE Precios_Actuales (
    id_precio SERIAL PRIMARY KEY,
    id_moneda INTEGER,
    precio_actual DECIMAL(10, 2),
    fecha_actualizacion DATE,
    FOREIGN KEY (id_moneda) REFERENCES Monedas(id_moneda)
);
```
## Especificación de las claves primarias y análisis de las relaciones.

* La tabla Usuarios tiene una clave primaria (id_usuario).
* La tabla Monedas tiene una clave primaria (id_moneda).
* La tabla Transacciones tiene una clave primaria (id_transaccion) y claves foráneas que hacen referencia a las tablas Usuarios y Monedas.
* La tabla Precios_Actuales tiene una clave primaria (id_precio) y una clave foránea que hace referencia a la tabla Monedas.

## Identifica tipos de entidades, atributos y relaciones.
* **Tipos de entidades**: Usuarios, Monedas, Transacciones y Precios_Actuales.

* **Atributos**: Cada tabla tiene atributos específicos que se definen en la creación de la tabla.

* **Relaciones**:  Las relaciones se establecen mediante claves foráneas que hacen referencia a las claves primarias de otras tablas, como se especifica en la creación de las tablas.

## Normaliza para reducir redundancia y desnormaliza para mejorar el rendimiento.

Para la normalización, cada tabla debe estar en la primera forma normal (1NF), lo que significa que cada columna contiene un solo valor y que no hay duplicados en las filas. Ajustar las estructuras de las tablas según sea necesario para cumplir con este principio.

Para la desnormalización, evaluamos si hay áreas de la base de datos donde la desnormalización podría mejorar el rendimiento de las consultas. Esto puede implicar la introducción de redundancia controlada para evitar la unión de tablas en operaciones frecuentes. Por ejemplo, crear una vista que combine la información de varias tablas para reducir la necesidad de unir tablas en consultas comunes.

## Diagrama Entidad-Relacion
![DR](https://github.com/TSSW2024/sprint-2/assets/165086815/5e1f9192-2d50-44f9-a82a-3879f489f2ec)
