### ISSUE TITLE
(Feature - Frontend) Vista de Perfil Usuario

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/sprint-2#2]
## Descripción
Diseñar un nuevo botón de perfil que se ubicará en la parte arriba a la derecha en forma de circulo (Estará presentes en todo en home, es decir, si se cambió de vista a cartera o mercado el botón estará en el mismo lado)

## Tareas
* [x] Nombre de usuario: Implementar un Campo de texto con el Nombre de usuario

* [ ] ID: Implementar un Campo de texto con el ID
* [x] Correo electrónico: Implementar un Campo de texto con el Correo electrónico
* [x]  Foto: Implementar un Campo donde se pueda subir una Foto
* [x] Link: Link de los diferentes contactos del clientes (Discord,Github,Facebook) enlaces con sus redes sociales

> 

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 06-05-2024

**Comment by Buakir** [comment]
Hice un prototipo en el figma, necesito feedback para ya empezar de lleno con el código

**Comment by zkodah** [comment]
me parece adecuada.
