### ISSUE TITLE
(Feature - Frontend) Cambio de Navbar 1

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/sprint-2#3]
## Descripción
El Navbar debe ser modificado para incluir solo tres elementos: "Mercado", el logo de la aplicación y "Cartera".

## Tareas
* [x] : Implementar iconos para cada elemento del Navbar.

* [x] : Al hacer clic en el botón central (el logo de la aplicación), se debe abrir un overlay que emerge desde la parte inferior de la pantalla hacia arriba. Este overlay contendrá las opciones "Comprar", "Vender" y "Convertir"
* [x] : Cada una de estas opciones debe redirigir a una página en blanco con un título correspondiente.

> Es necesario crear las páginas a las que se redirige al hacer clic en las opciones del Navbar. Cada una de estas páginas debe tener su propia carpeta para no romper la estructura existente y permitir que otros desarrolladores trabajen en ellas sin alterar el curso lógico del proyecto. Las páginas deben estar en blanco, solo con un título que indique su contenido.

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 27-04-2024

**Comment by SmnZin** [comment]
ta ready funcionalmente, solo faltaria que los compas del front decidan que colocar en el icono central

**Comment by zkodah** [comment]
@Buakir Envíale el Icono

**Comment by Buakir** [comment]
![Sin título(1)](https://github.com/TSSW2024/sprint-2/assets/63122266/af73f865-1c48-43e7-bcbb-441e9fe4de93)

Aquí esta el icono provisorio de la aplicación, coloquemos este por ahora y cuando tengamos un acuerdo mutuo en la identidad visual en general de la app, crearemos uno nuevo uwu
