### ISSUE TITLE
(Feature - Qa) Autenticacion

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/sprint-2#4]
## Descripción
Se busca implementar el tema de la Autenticación al ingresar a la aplicación o Registro de un usuario

## Tareas
* [x] Pruebas de Autenticación y Registro : El QA debe diseñar y ejecutar pruebas exhaustivas para verificar que el proceso de autenticación y registro funcione correctamente. Esto incluye probar diferentes escenarios, como ingreso con credenciales válidas, credenciales inválidas, contraseñas incorrectas, etc.
* [x] Validación de Flujo de Usuario: El QA debe asegurarse de que el flujo de autenticación y registro sea intuitivo y sin errores. Esto implica verificar que los mensajes de error sean claros, que los campos obligatorios estén marcados correctamente y que los usuarios sean redirigidos correctamente después de autenticarse o registrarse.

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 06-05-2024

**Comment by VlackVist** [comment]
Parte de esto lo investigué en el sprint anterior. Pero ya estuve programando con Selene/Selenium rutinas que se conecten a mi.utem con las respectivas credenciales. Adjunto un video del codigo en python que es capaz de conectarse a mi.utem.cl con las credenciales que se le coloquen. [Demostración video Youtube](https://youtu.be/wavapj4DpW8)
Adicionalmente lo que hace este codigo es acceder a un driver de chrome para poder utilizarlo y mediante este mismo driver poder realizar los ingresos a la web. La busqueda de campos se hace mediante XPATH que lo hace es buscar directamente dentro del codigo HTML las etiquetas que se les especifique con los parametros a buscar.

Adjunto codigo en python que accede a dependencias selenium para hacer uso de busquedas con XPATH y acceso a web mediante la "pulsacion" de teclas

```
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://mi.utem.cl/pasaporte/")
time.sleep(1)
#correo=driver.find_element(By.XPATH,'//form/div/label[contains(text(),"Usuario")]')
usuario=driver.find_element(By.XPATH,'//input[@id="id_txt_usuario"]')
usuario.send_keys("Usuario")

#time.sleep(5)
password=driver.find_element(By.XPATH,'//input[@id="id_txt_password"]')
password.send_keys("Contraseña")

#driver.implicitly_wait(10)
inicio=driver.find_element(By.XPATH,'//button[@type="submit"]')
inicio.click()

time.sleep(5)

driver.quit()
```

**Comment by VlackVist** [comment]
El flujo para llevar acabo la autenticacion y registro dentro de la aplicación es muy intuitivo y facil de seguir. Ya que lleva botones grandes e intuitivos con colores que llaman la atención del usuario.

Inicio de sesión con credenciales erroneas:
![imagen](https://github.com/TSSW2024/sprint-2/assets/119820077/06111ce2-4045-4f10-b2fb-1658118d5858)
Esto funciona correctamente

El botón en la parte inferior para crear una cuenta es funcional, es decir que puede ser pulsado y nos redirige a un formulario de registro: 
![imagen](https://github.com/TSSW2024/sprint-2/assets/119820077/435db5ca-5473-4c84-b5de-4f952bb25598)
Cada uno de los campos es rellenable pero claramente el botón que enviaría el formulario a ser registrado en la  base de datos aun no está funcional ya que debe realizar una conexión a la  misma aun.
Por lo que actualmente soy incapaz de evaluar tanto el caso de inicio de sesión exitoso. Tampoco es posible evaluar el registro de usuario para un caso exitoso y uno fallido ya que al no estar implementado con base de datos las comprobaciones de campos no  están hechas, es decir que puede ingresar como fecha de nacimiento el mismo dia de logeo, puedo colocar cualquier cosa en los campos correo, nombre, etc.
Lo único validable y en funcionamiento ahora mismo es el botón de aceptar los términos y condiciones ya que si no esta seleccionada esta opción directamente no nos deja pulsar el botón de registrarse. Por lo demás solo es un formulario rellenable sin comprobaciones ni respaldos en un base de datos
