### ISSUE TITLE
(Spike - Qa) Proceso para recopilación de información 

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/sprint-2#6]
## Descripción
En este issue de spike, la de recopilación de información, en el contexto de un informe de pruebas de penetración, describirá un hallazgo u observación que puede indicar áreas de potencial riesgo o vulnerabilidad en el proyecto, basándose únicamente en la información recopilada sin interacción intrusiva. Estos hallazgos son cruciales porque pueden revelar vulnerabilidades que podrían ser explotadas con fines maliciosos.

## Tareas
* [x] : Identificación e investigación de Dominios y Subdominios (con diferentes herramientas), para ayudar a mapear la superficie de ataque.
* [x] : Consultas WHOIS para evaluación de filtración de información sensible y obtener información registrada sobre el dominio objetivo, incluyendo fechas de registro, contactos y servidores.
* [x] : Emplear operadores de búsqueda avanzados en Google (conocidos como Google Dorks o Google Hacking) para encontrar información sensible o expuesta accidentalmente, como archivos de configuración, backups, o documentos internos.
* [x] : Detección de servicios y versiones del servidor de manera pasiva con la herramienta NMAP, ademas de un análisis de DNS.

> Esta issue deberá ser colaborada por todos los Qa y Sec Lead, en conjunto de su implementación, y quedará asignada a un responsable.

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 06-05-2024

**Comment by VlackVist** [comment]
Aplicaciones web para la investigación de dominios y subdominios, con posibilidad de geolocalizar y obtención de IP.
https://subdomainfinder.c99.nl/
https://dnsdumpster.com/

**Comment by VlackVist** [comment]
![imagen](https://github.com/TSSW2024/sprint-2/assets/119820077/0d5eaed8-8961-4c93-9c56-2d12381610a5)
Algunos operadores frecuentes para especificar y acotar búsquedas de información con Google Dork

**Comment by VlackVist** [comment]
Consultas WHOIS: https://whois.gandi.net/es
https://www.whois.com/whois/
Ambas aplicaciones son web y probé con dominios de utem y encontré fechas de creación y de expiracion del dominion facilmente. Además de identificar que sus dominios estan bajo la empresa NIC.cl

A su vez encontré otra pagina web que puede servir tanto para buscar dominios y subdominios como para obtener algunos datos obtenibles con consultas WHOIS. Tambien brinda posibilidad de analizar el estado del DNS y las brechas de seguridad que puede tener. https://dns-analyzer.ncu.edu.tw/

**Comment by VlackVist** [comment]
Comencé a trabajar con NMAP y segui trabajando con los servidores disponibles de utem.cl especificamente con uno bajo el subdominio "cache.utem.cl" la dirrecion IP de este host es: 146.83.180.8.
Se encontraron superficialmente 3 servicios que interactúan dentro del host, y fueron 3: 
![imagen](https://github.com/TSSW2024/sprint-2/assets/119820077/856b8ae5-d648-4de8-a7ef-2c81ffd32488)
Dentro del servicio de dominio encontramos la versión, el puerto(53) y el protocolo. Además de saber que el servicio esta activo
Tambien se encontro el http el cual trabaja con el puerto 8008:
![imagen](https://github.com/TSSW2024/sprint-2/assets/119820077/61b82dd6-7016-4b20-aad5-1f9cd44ba777)
Y por ultimo un servicio que se llama Ident y no aparentemente no esta activo. Igualmente el puerto detectado para este servicio fue el 113:
![imagen](https://github.com/TSSW2024/sprint-2/assets/119820077/155864fa-bd4d-4acd-b728-40d3eea5ccaa)

El host en general tiene un buen tiempo de respuesta asi que no presenta una latencia perceptible, "Host is up (0.0054s latency)."

Para el analisis de DNS se detectó lo siguiente "bind.version: 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.13"
Se trata de una version relacionada con el servidor BIND, y a su vez podemos determinar que este trabaja con una distribución de Linux (Red Hat Enterprise Linux 7) 

![imagen](https://github.com/TSSW2024/sprint-2/assets/119820077/1ea7eb70-26ab-4ccb-9907-3796a9858697)
A su vez esto nos permite identificar varias cosas del servidor, sabemos que el protocolo TCP con el que trabaja es bueno ya que posee una dificultad alta lo que lo hace dificil la prediccion del protocolo.

![imagen](https://github.com/TSSW2024/sprint-2/assets/119820077/b17cd162-2a0f-4ba5-a121-03c565b977fe)
A su vez el traceroute detectó 4 posibles IP que se comunican con el servidor objetivo, pueden significar distintos escenarios, quizas VPN, quiza algun servidor que se comunica o puede ser incluso la IP que se le brinda a NMAP para comenzar el analisis del sistema

**Comment by VlackVist** [comment]
Hay un punto especifico del issue que no logró entender perfectamente y es el que está sin resolver. Si pueden adjuntar información complementaria lo agradecería
