### ISSUE TITLE
(Spike - Infraestructure) Base de datos

### ISSUE THREAD

**Issue by zkodah** [TSSW2024/sprint-2#7]
## Descripción
En esta Spike se busca recopilar información y generar una opción robusta para la ocupación de una base de datos correcta para nuestro proyecto

## Tareas
* [x] :  Realizar un estudio de mercado sobre los DBMS disponibles para el uso de Backend desarrollo
* [x] : Preseleccionar las opciones que mejor se ajusten a los requisitos identificados a nuestra aplicación
* [x] : Implementar pruebas de concepto con opción elegida de la Base de datos

> 

## Fecha de Vencimiento
Se ha definido la fecha de entrega para el día 06-05-2024

**Comment by JoseMalcaR** [comment]
## Identificacion de requisitos

* **Alta disponibilidad y fiabilidad**:La aplicación debe estar disponible en todo momento para garantizar que los usuarios puedan acceder a sus cuentas y realizar transacciones en cualquier momento del día. Por lo tanto, el DBMS debe ofrecer capacidades de alta disponibilidad y replicación para minimizar el tiempo de inactividad y garantizar la continuidad del negocio.
* **Rendimiento escalable**: Dado que las aplicaciones de trading pueden experimentar picos de carga significativos durante períodos de alta actividad del mercado, el DBMS debe ser capaz de escalar horizontal y verticalmente para manejar grandes volúmenes de transacciones y consultas concurrentes sin degradación del rendimiento.
* **Transacciones ACID**: La integridad de los datos es fundamental en una aplicación de trading. El DBMS debe admitir transacciones ACID (Atomicidad, Consistencia, Aislamiento y Durabilidad) para garantizar la coherencia de los datos y prevenir la corrupción en caso de fallas del sistema.
* **Baja latencia y tiempo de respuesta rapida**:Los traders necesitan ejecutar transacciones rápidamente para aprovechar las oportunidades del mercado. Por lo tanto, el DBMS debe proporcionar tiempos de respuesta bajos y baja latencia para garantizar una ejecución rápida de las transacciones.
* **Seguridad robusta**:La seguridad de los datos es crítica en una aplicación de trading, especialmente cuando se trata de información financiera confidencial. El DBMS debe ofrecer sólidas características de seguridad, incluyendo autenticación de usuarios, control de acceso granular, cifrado de datos en reposo y en tránsito, y auditoría de registros para cumplir con los estándares de seguridad y regulaciones del sector.
* **Integracion con otras tecnologias**: La aplicación de trading puede requerir integración con otros sistemas y tecnologías, como sistemas de mensajería, API de terceros, servicios de streaming de datos en tiempo real, etc. Por lo tanto, el DBMS debe ser compatible con estas tecnologías y ofrecer capacidades de integración flexibles.
* **Capacidades analiticas**: Además de admitir transacciones en tiempo real, el DBMS también puede necesitar capacidades analíticas para realizar análisis de datos históricos, generación de informes, análisis de tendencias del mercado, etc.
  
## Opciones Disponibles:

1. **PostgreSQL**: Es una base de datos relacional de código abierto que ofrece una sólida combinación de rendimiento, escalabilidad y características avanzadas. Es conocida por su soporte ACID, alta disponibilidad, capacidades de replicación y extensibilidad a través de extensiones y funciones personalizadas. PostgreSQL es una opción popular para aplicaciones críticas y de alto rendimiento, incluyendo aplicaciones financieras.
2. **MySQL**: Es otra opción de base de datos relacional de código abierto ampliamente utilizada en aplicaciones de alta disponibilidad. Ofrece capacidades ACID, escalabilidad horizontal y vertical, y un sólido rendimiento en entornos de producción. MySQL es conocida por su facilidad de uso y amplia adopción en la comunidad, lo que la convierte en una opción popular para una variedad de aplicaciones, incluyendo aplicaciones de trading.
3. **MongoDB**: Es una base de datos NoSQL que se destaca por su flexibilidad, escalabilidad y rendimiento. Es especialmente adecuada para aplicaciones que manejan grandes volúmenes de datos no estructurados o semi-estructurados, como datos de mercado en tiempo real. MongoDB ofrece replicación automática, particionamiento y capacidad de escala horizontal, lo que la hace adecuada para aplicaciones que requieren alta disponibilidad y rendimiento.
4. **Casandra**: Apache Cassandra es una base de datos distribuida NoSQL diseñada para ofrecer escalabilidad lineal y alta disponibilidad en entornos distribuidos. Es especialmente adecuada para aplicaciones que requieren almacenamiento y recuperación de datos a alta velocidad, como aplicaciones de trading que manejan grandes volúmenes de transacciones en tiempo real. Cassandra ofrece características como replicación activa-activa, tolerancia a fallos y capacidades de recuperación ante desastres.
5. **Redis**: Redis es una base de datos en memoria de código abierto que ofrece un rendimiento extremadamente rápido y baja latencia. Es especialmente adecuada para aplicaciones que requieren acceso rápido a datos en tiempo real, como la gestión de sesiones de usuario, la cache de datos y la gestión de colas. Redis ofrece capacidades de replicación y alta disponibilidad, lo que la hace adecuada para aplicaciones críticas como las de trading.
   
## Comparacion de caracteristicas

Como ya tenemos claro los requisitos y las bases de datos a elegir, vamos a comparar las caracteristicas de cada DBMS con los requisitos de nuestro proyecto.

1. Si priorisamos la consistencia de los datos y necesitamos una base de datos relacional robusta, **PostgreSQL** sería una excelente opción ya que ofrece soporte completo de ACID, alta disponibilidad, escalabilidad y una amplia gama de características avanzadas.
2. Si vamos a trabajar con grandes volúmenes de datos no estructurados o semi-estructurados y necesitamos escalabilidad horizontal: **MongoDB** podría ser la mejor opción. Su arquitectura NoSQL flexible y su capacidad de escala horizontal la hacen adecuada para aplicaciones que manejan grandes cantidades de datos en tiempo real.
3. Si la velocidad y la baja latencia son críticas y podemos tolerar una eventual pérdida de datos, **Redis** podría ser una opción a considerar. Su almacenamiento en memoria y su rendimiento extremadamente rápido lo hacen adecuado para aplicaciones que requieren acceso rápido a datos en tiempo real, como la gestión de sesiones de usuario y la cache de datos.
4. Si necesitamos una base de datos distribuida altamente escalable y tolerante a fallos: **Cassandra** sería una opción sólida. Su arquitectura distribuida y su capacidad de escala lineal la hacen adecuada para aplicaciones que requieren alta disponibilidad y rendimiento en entornos distribuidos.
5. Si preferimos una solución de base de datos relacional ampliamente adoptada y con una gran comunidad de usuarios: **MySQL** sería una opción confiable ya que ofrece características sólidas de ACID, escalabilidad y una amplia gama de herramientas y recursos de la comunidad.
   
## Opcion Elegida

Teniendo en cuenta las caracteristicas de cada base de datos, y que la mayoria son de codigo abierto o tienen una version gratuita, tambien considerando las preferencias de los desarrolladores backend, la opcion elegida es **PostgreSQL**.
